[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy - allows Cal.com and other embeds
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://embed.cal.com https://app.cal.com https://cal.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://embed.cal.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://api.cal.com https://embed.cal.com;
      frame-src 'self' https://cal.com https://embed.cal.com https://app.cal.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://embed.cal.com;
      upgrade-insecure-requests;
    '''
    
    # Permissions Policy - lock down unused features
    Permissions-Policy = '''
      camera=(),
      microphone=(),
      geolocation=(),
      payment=(),
      usb=(),
      magnetometer=(),
      gyroscope=(),
      accelerometer=(),
      ambient-light-sensor=(),
      autoplay=(),
      encrypted-media=(),
      fullscreen=(self),
      picture-in-picture=()
    '''

# Cache static assets with hash
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML pages - shorter cache with revalidation
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

# API routes and dynamic content
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects for SEO (add your Squarespace redirects here later)
# [[redirects]]
#   from = "/old-squarespace-page"
#   to = "/new-astro-page"
#   status = 301

# Force HTTPS
[[redirects]]
  from = "http://shootingquarterly.com/*"
  to = "https://shootingquarterly.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.shootingquarterly.com/*"
  to = "https://shootingquarterly.com/:splat"
  status = 301
  force = true

# Choose one: www or non-www (currently set to non-www)
[[redirects]]
  from = "https://www.shootingquarterly.com/*"
  to = "https://shootingquarterly.com/:splat"
  status = 301
  force = true

# SPA fallback for client-side routing (if needed later)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200